#!/bin/bash
set -e
OUTPUT="output"
BLOG="$OUTPUT/blog"
mkdir -p "$OUTPUT" "$BLOG"

DATE_HUMAN=$(date "+%A, %d %B %Y %H:%M:%S %Z")
STAMP=$(date "+%Y-%m-%d_%H-%M-%S")
POST_SLUG="post-$STAMP.html"
POST_PATH="$BLOG/$POST_SLUG"

# Create a tiny daily post
cat > "$POST_PATH" <<HTML
<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8">
<title>Daily Update — $STAMP</title></head>
<body>
<h1>Daily Update ($DATE_HUMAN)</h1>
<p>Auto-generated by GodAI Genesis.</p>
</body></html>
HTML

# Update feed.json (append new item)
FEED="$BLOG/feed.json"
if [ ! -f "$FEED" ]; then
  echo '{ "items": [] }' > "$FEED"
fi

# Use jq if available; otherwise simple append
if command -v jq >/dev/null 2>&1; then
  tmp=$(mktemp)
  jq --arg u "./$POST_SLUG" --arg t "Daily Update $STAMP" --arg d "$DATE_HUMAN" \
     '.items |= ([{"url":$u,"title":$t,"date":$d}] + .) | .items |= .[0:50]' "$FEED" > "$tmp"
  mv "$tmp" "$FEED"
else
  # naive prepend (keeps file small)
  CONTENT=$(cat "$FEED")
  echo '{ "items": [{"url":"./'"$POST_SLUG"'","title":"Daily Update '"$STAMP"'","date":"'"$DATE_HUMAN"'"}] }' > "$FEED"
fi

# Touch homepage time
sed -i 's/Last updated:.*/Last updated: '"$DATE_HUMAN"'</' "$OUTPUT/index.html" 2>/dev/null || true
echo "[AutoPage] Generated $POST_PATH"
