import os, datetime, random, textwrap
from utils import log_to, send_telegram

AFFIL_ID = "gogreenstore-21"  # Amazon.in
POST_DIR = os.path.expanduser("~/godai-genesis/uploads/blog")

TOPICS = [
    ("Solar Power Basics", "https://www.amazon.in/s?k=solar+panel&i=electronics&tag={aid}"),
    ("Home Energy Audits", "https://www.amazon.in/s?k=power+meter&tag={aid}"),
    ("Water Saving Hacks", "https://www.amazon.in/s?k=water+saving&tag={aid}"),
    ("Composting 101", "https://www.amazon.in/s?k=compost+bin&tag={aid}"),
    ("Air Quality & Plants", "https://www.amazon.in/s?k=indoor+plants&tag={aid}"),
    ("EV Charging at Home", "https://www.amazon.in/s?k=ev+charger&tag={aid}"),
    ("LED vs CFL", "https://www.amazon.in/s?k=led+bulb&tag={aid}"),
    ("Rainwater Harvesting", "https://www.amazon.in/s?k=rainwater+harvesting&tag={aid}"),
]

def make_post():
    os.makedirs(POST_DIR, exist_ok=True)
    today = datetime.date.today().isoformat()
    title, link_tmpl = random.choice(TOPICS)
    slug = title.lower().replace(" ", "-")
    link = link_tmpl.format(aid=AFFIL_ID)
    fn = os.path.join(POST_DIR, f"{today}-{slug}.md")
    if os.path.exists(fn):
        return fn, False

    md = f"""# {title}

*Date: {today}*

We Rise Together Forever 🌱🚀

**Quick Takeaways**
- Practical, doable changes you can apply today.
- Small steps compound over time.
- Track your impact and share progress.

**Recommended tools on Amazon.in**
- Curated search: [{title}]({link})

---

> This post was auto-generated by GodAI Genesis.
"""
    with open(fn, "w", encoding="utf-8") as f: f.write(textwrap.dedent(md))
    return fn, True

if __name__ == "__main__":
    fn, created = make_post()
    msg = f"📰 Daily post {'created' if created else 'already exists'}: {os.path.basename(fn)}"
    log_to("autoblogger.log", msg); send_telegram(msg)
