import os, datetime, shutil
from utils import log_to, send_telegram

UP_DIR = os.path.expanduser("~/godai-genesis/uploads")
BLOG_DIR = os.path.join(UP_DIR, "blog")
DASH_DIR = os.path.join(UP_DIR, "dashboard")
LOG_DIR = os.path.expanduser("~/godai-genesis/logs")

def safe_count(path):
    try:
        return len([p for p in os.listdir(path) if os.path.isfile(os.path.join(path,p))])
    except FileNotFoundError:
        return 0

if __name__ == "__main__":
    os.makedirs(DASH_DIR, exist_ok=True)
    today = datetime.date.today().isoformat()
    blog_count = safe_count(BLOG_DIR)
    log_size = 0
    for root, _, files in os.walk(LOG_DIR):
        for f in files:
            fp = os.path.join(root, f)
            try: log_size += os.path.getsize(fp)
            except: pass
    kb = max(1, log_size//1024)
    report = f"""Genesis Daily Report - {today}

We Rise Together Forever 🌱

Blog posts total: {blog_count}
Approx log footprint: {kb} KB

UPI: 919209705081@sbi
Affiliate: Amazon.in ID gogreenstore-21

-- Auto-generated by GodAI Genesis
"""
    out = os.path.join(DASH_DIR, f"report-{today}.txt")
    with open(out, "w", encoding="utf-8") as f: f.write(report)
    msg = f"📊 Income/Status report updated: {os.path.basename(out)}"
    log_to("health_history.log", msg); send_telegram(msg)
