name: AutoPage Daily Build

on:
  schedule:
    - cron: "0 0 * * *"   # Every day at midnight UTC
  workflow_dispatch:       # Allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate homepage
        run: |
          chmod +x autopage.sh
          ./autopage.sh

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
