name: Build & Sign Genesis APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Cordova
        run: npm install -g cordova

      - name: Install Dependencies
        run: npm install

      - name: Build Android APK
        run: |
          cd cordova-app
          cordova platform add android || true
          cordova build android --release

      - name: Sign APK
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: cordova-app/platforms/android/app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
          alias: ${{ secrets.ANDROID_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}

      - name: Upload Signed APK
        uses: actions/upload-artifact@v4
        with:
          name: genesis-signed-apk
          path: cordova-app/platforms/android/app/build/outputs/apk/release/*.apk
