name: Netlify Deploy
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    if: ${{ secrets.NETLIFY_AUTH_TOKEN && secrets.NETLIFY_SITE_ID }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nwtgck/actions-netlify@v3.0
        with:
          publish-dir: "docs"
          production-deploy: "true"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
